language: go
deploy:
  provider: heroku
  api_key:
    secure: NmHj2AzdOPshGH1JwmY0QvhNigBMAS++7LyDYSxDJysoEUW/MKHpeL1dsatwEbEz+DWmMWnvZEIIRWIvX3nHQc4j94L0R/HeM+WwWsy61C3wymmYjNA0IwGoTkqCR3ueeb+hms7t0fEAK9LX7vdoAfZxW4algNbdAqYcXwRMsW8f6KNWTyBcNPJ7Rka5YEvFqU9Vp2i5rlXFj1uLCIMqw59vBq8sxkwMj0bivdDiWIgDtXWUuA1QmytiBkZnDsRV2G1upfXKznXT9K1kZDf17qSkQVDVmuwSXBUqQVhtOrZDSKQomTP6XGiPhVR4nG6Q7W0xPkomsBgoSeg1u9dAJoWhnMeDNxrspBu/iDmpDPXKCTuLz+VHFAsLCoylObDZ8xyIX0ewMOJFcRQBT3gHzbYjtnap9T5cAV9eWC9wsf0KyeiyK5TqlGW5h1Cl0HPMmMoaNETvXD4UmSZMuEnkHqe+viuTFCFy16o6vHgw2S9OKHP3fhh5I936j5VkKmCLVZts9WoeWZ3Wdm8ssBsNfDeEx0OhcLKQJy95fEfNGz2uMhUUPFKonRNkakhw6R0ShA5iYUxsmS4NzDw/hIusqh96WwuO1y1pllFJMj7SYnBoMoCFll4iRpC/rXISwP5jIM7ukGHh/2APRqbgmqXe1L9c1TRujEwTkuQC7oRlObs=
  app: lab1-ci-cd-ed-asriyan
env:
  - GO111MODULE=on
notifications:
  email: false
