//
// Created by ed on 07.03.17.
//

#ifndef INC_3DVIEW_ERRORS_H
#define INC_3DVIEW_ERRORS_H

typedef enum {
	NONE,
	OUT_OF_MEMORY,
	NOT_INITIALIZED,
	ALREADY_INITIALIZED,
	MODEL_NOT_LOADED,
	UNABLE_TO_OPEN_FILE,
	INVALID_FILE,
	UNKNOWN_COMMAND,
} error_t;

#endif //INC_3DVIEW_ERRORS_H
